### ISSUE TITLE
Wrong values in env vars

### ISSUE THREAD

**Issue by avnerenv0** [jacob-meacham/serverless-plugin-git-variables#29]
My lambda function is deployed with env var `GIT_BRANCH` with value `HEAD`
and with env var `GIT_BRANCH` with value `source`.

This happens when it's deployed using https://seed.run/

Any ideas how can this be avoided? Thanks

**Comment by jacob-meacham** [comment]
Hi @avnerenv0, thanks for the report! I'm not familiar with seed so I'll need to try it out. Do you have any other repro steps or an open source minimal version that exhibits this behavior?

**Comment by avnerenv0** [comment]
No sorry.
I eventually understood that seed.run, like some other CI platforms, runs the code in a detached head state. My work around was -
`export GIT_BRANCH=$(git show -s --pretty=%D HEAD | awk -F'/' '{print $2}')`

**Comment by jacob-meacham** [comment]
Awesome, glad you were able to figure this out - and thanks for posting your workaround!
