### ISSUE TITLE
Document isDirty

### ISSUE THREAD

**Issue by robatwilliams** [jacob-meacham/serverless-plugin-git-variables#33]
The readme mentions the `GIT_IS_DIRTY` environment variable, but not  `${git:isDirty}`

**Comment by jacob-meacham** [comment]
@robatwilliams thanks for the issue! Fixed in https://github.com/jacob-meacham/serverless-plugin-git-variables/commit/aa3ce0ac8e02867d90e2234c96889300658e6ae1
