### ISSUE TITLE
Display GIT_USER and GIT_EMAIL by default

### ISSUE THREAD

**Issue by navrkald** [jacob-meacham/serverless-plugin-git-variables#53]
Currently GIT_USER and GIT_EMAIL are not displays automatically and have to be added to environment variables and AWS tags manually like this:
```
    GIT_USER: ${git:user}
    GIT_EMAIL: ${git:email}
```
This variables should be added automatically.

**Comment by jacob-meacham** [comment]
Hey @navrkald this is expected behavior as we didn't want to automatically populate something that identified a particular user. As you describe, you can work around this issue in the case where you'd like to explicitly set the user/email. Thanks!
