### ISSUE TITLE
Old version of babel-runtime with deprecated core-js

### ISSUE THREAD

**Issue by coyoteecd** [jacob-meacham/serverless-plugin-git-variables#58]
I've tried importing serverless-plugin-git-variables in my Serverless project I see it has a dependency on [babel-runtime](https://www.npmjs.com/package/babel-runtime). Last publish is 3 years ago and I get a warning that it depends on a now-deprecated version of core-js.

Current version of babel runtime is [@babel/runtime](https://www.npmjs.com/package/@babel/runtime). Would be great to use it and get rid of the core-js warning... Would be even nicer to have the plugin not need it at all, since installing it brought me 51 dependent packages to node_modules.

**Comment by bitsofinfo** [comment]
same, getting error on install

**Comment by coyoteecd** [comment]
@bitsofinfo for what is worth, for my project I ended up creating my own version of a plugin that exposes git info as Serverless variables, see https://github.com/coyoteecd/serverless-git-info

**Comment by jacob-meacham** [comment]
Thnks @coyoteecd, I'm publishing a new version that no longer relies on babel runtime

**Comment by jacob-meacham** [comment]
Published as 5.0.0
