### ISSUE TITLE
${git:sha1} is sporadically empty

### ISSUE THREAD

**Issue by jaikdean** [jacob-meacham/serverless-plugin-git-variables#7]
We are using `${git:sha1}` to version a cache, but it's sometimes empty. I couldn't track down any pattern to this, but for now we've just implemented our own variable in a JS file using `child_process.execSync('git rev-parse HEAD').toString('utf-8').trim();`, but wanted to report the issue.

**Comment by jacob-meacham** [comment]
Thanks for the report @jaikdean! This plugin was built before the ability to define variables via JS existed but that's a very reasonable way to go. I'll still take a look at this issue.
