### ISSUE TITLE
Integration with Serverless Framework v3

### ISSUE THREAD

**Issue by mnapoli** [jacob-meacham/serverless-plugin-git-variables#83]
Hi 👋 , Serverless Framework core team here!

We're working on the v3 beta version right now. The v3 will include a redesigned CLI output:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/720328/139266855-7c0c15e1-9201-48b6-92f0-db6af2da4d11.png">

You can try the v3 beta with: `npm i serverless@pre-3`

I had a quick look at the code of this plugin and it seems like you don't log anything to the CLI output. So I don't think there is anything to change in this plugin.

Let me know if I'm wrong. I'd be happy to help in any way if needed.

Feel free to close this issue if there is nothing to do indeed.

---

In any case, here is some more information on new plugin API we have added, in case you are curious:

- [Video introduction (Youtube)](https://www.youtube.com/watch?v=K3IhZ9fImk4)
- [Documentation of the new API](https://www.serverless.com/framework/docs/guides/plugins/cli-output)

Any feedback is appreciated on all that!

**Comment by jacob-meacham** [comment]
Hi @mnapoli thanks - I was able to get it working with Serverless v3. However, in v1, I was able to programmatically create a Serverless instance in my tests. That no longer works, which means writing tests is tougher - is there a recommended way to test plugins now?

**Comment by mnapoli** [comment]
Awesome, thanks for the update!

Regarding tests, there is the https://github.com/serverless/test package that should help with that. Maybe @medikoo can answer that better than me as well.

**Comment by medikoo** [comment]
@jacob-meacham for testing, I recommend using tool we're relying internally `runServerless`(https://github.com/serverless/test/blob/master/docs/run-serverless.md), but note that for v3, it changed internally a bit, and changed version is published with `@serverlesss/test@pre-9` pre-release)
