### ISSUE TITLE
Deployment issue in 2.1.0

### ISSUE THREAD

**Issue by campadrenalin** [jacob-meacham/serverless-plugin-git-variables#9]
This isn't a source problem, but the latest version uploaded to `npm` is missing the `lib` directory. This means that `require('serverless-plugin-git-variables')` doesn't work (package.json `main` points to a path that doesn't exist, `lib/index.js`), so SLS cannot import the plugin anymore. It looks like `src` is available, but uses `import`, which doesn't work out of the box. So we do need the build tooling.

Thank you for your time, and for merging git:message! Sorry to add hassle to your day, that certainly isn't my intention.

**Comment by jacob-meacham** [comment]
@campadrenalin My mistake, sorry about that! Just released hotfix 2.1.1 which should hopefully be correct.

Thanks!

**Comment by campadrenalin** [comment]
@jacob-meacham Works for me, thank you!
